// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const envUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const envKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL =
  envUrl && String(envUrl).trim() !== "" ? envUrl : "http://127.0.0.1:54321";
const SUPABASE_PUBLISHABLE_KEY =
  envKey && String(envKey).trim() !== "" ? envKey : "dev-placeholder-anon-key";

if (!envUrl || !envKey) {
  console.warn(
    "[Supabase] NEXT_PUBLIC_SUPABASE_URL and/or NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY are missing; using placeholders."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window === "undefined" ? undefined : localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
