// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const envUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const envKey = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL = envUrl?.trim() || "https://ytvncpspjbdusdiabyel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = envKey?.trim() || "sb_publishable_jw49Nh9BGLc4w22HMVGpOA_Un1UtRYg";

if (!envUrl || !envKey) {
  console.warn(
    "[Supabase] Vercel environment variables are missing; using the configured public project credentials."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window === "undefined" ? undefined : localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
